### ISSUE TITLE
Use case 2 graph is missing its data

### ISSUE THREAD

**Issue by Etoebben** [computationalmystic/augur-group26#11]
The use case 2 graph appears as a shell and needs data added to it.

I would like to see data in the graph that represent the number of commits a user added

**Comment by sgoggins** [comment]
Be more specific about what "graph from use case 2" is, and what data you think is missing. A screen shot would not hurt. It would help a lot. Make the issue more descriptive.

**Comment by Etoebben** [comment]
The use case 2 is the zoomable graph. The encoding for the data needed to be set up. While the graph outline is set up it is not showing any lines that represent the data.

**Comment by Etoebben** [comment]
There was a lot of work that need to be done. It was isolated to the zoomChart.vue file. The changes can be seen in the "working on the use case 2" commit. The changes that were made to the data, that let it take form are in lines 65 to line 242
